### ISSUE TITLE
config: improve format of inertia configuration

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/inertia#101]
PR #99 introduces TOML configuration for Inertia. Being able to source control basic remote settings (IP, etc) might come in handy for some people, but there are certain things we probably don't want in there if someone chooses to commit the configuration file:

- Inertia daemon key: this one should definitely offer the option to be stored/read from elsewhere

- Local PEMfile location? Perhaps not critical, but a command line option to change the location might come in handy

An idea would be to allow remote config to be pulled from `ENV`

**Comment by iKevinY** [comment]
Just some thoughts: instead of having secrets live in `Inertia.toml`, leave that file specifically for project configuration. Then have Inertia read from a file like `~/.inertia-secrets`, which is a JSON that maps GitHub remotes to an object of the necessary secrets. This prevents the issue of secrets being "stuck" to the same file as your configuration.
