### ISSUE TITLE
Differences from dokku?

### ISSUE THREAD

**Issue by musabgultekin** [ubclaunchpad/inertia#613]
What are the most important differences from dokku? Its good to be documented or only exist in this issue.

**Comment by bobheadxi** [comment]
A few significant differences at a glance (disclaimer: never used dokku, and we started development on Inertia without knowing the project existed):

* inertia is primarily docker/docker-compose based, instead of using the heroku-style buildpacks. We had an experiment with using the same buildpacks that Dokku uses (I think?) (https://github.com/ubclaunchpad/inertia/pull/146), but this was removed because it wasn't very performant on the types of hosts we were targeting (free tier instances)
* I think dokku is agentless? At least I dont see any mention of a serverside dokku agent, and I couldnt find any documentation on setting up automated build/deploys on hooks with dokku, which is a big part of inertia ([docs](https://inertia.ubclaunchpad.com/#configuring-your-repository))

**Comment by bobheadxi** [comment]
Hey @musabgultekin , closing this for now since hopefully the explanation is discoverable via this issue - thanks for the question!
